### ISSUE TITLE
Make Fit Result Easily Accessible

### ISSUE THREAD

**Issue by ThomasLohnert** [ISISNeutronMuon/InstrumentScripts#26]
As a user I would like a convenient way to access the result of the last fit (e.g. peak, centre of mass, depending on type of fit). Something akin to `ReplayScan`, but for the Fit (although I believe we really are only interested in a single value rather than the whole `Fit` object).

**Comment by rprospero** [comment]
This should be possible via a fit on the replay scan, though it could probably use a more ergonomic wrapper.

**Comment by rprospero** [comment]
I've been looking over this again.  The "Replaying Scans" section of the tutorial explains how to perform a fit on the last scan

    fit = last_scan().fit(Gaussian)

If someone has a good name for it, we can write a wrapper for that line of code, but there's otherwise not much more to do here.  As for returning a single value instead of the whole object, the problem is that some models have multiple parameters and it's not always obvious which value should be returned.
